#!/bin/bash
touch $PWD/.commit

yq eval -j $PWD/config/rula.yaml &> $PWD/pytumeke/src/pytumeke/config/rula.json
yq eval -j $PWD/config/reba.yaml &> $PWD/pytumeke/src/pytumeke/config/reba.json
yq eval -j $PWD/config/niosh.yaml &> $PWD/pytumeke/src/pytumeke/config/niosh.json
yq eval -j $PWD/config/skeleton.yaml &> $PWD/pytumeke/src/pytumeke/config/skeleton.json
