#!/bin/bash
yq eval -j $PWD/config/rula.yaml &> $PWD/pytumeke/config/rula.json
yq eval -j $PWD/config/reba.yaml &> $PWD/pytumeke/config/reba.json
yq eval -j $PWD/config/niosh.yaml &> $PWD/pytumeke/config/niosh.json
