constants:
  black: &black
    Color:
      rgba(15, 15, 30, 0.9)

  light_green: &light_green
    Color:
      rgba(109, 208, 163, 1.0)

  green: &green
    Color:
      rgba(20, 210, 184, 1.0)

  orange: &orange
    Color:
      rgba(234, 130, 130, 1.0)

  red: &red
    Color:
      rgba(184, 15, 10, 1.0)

  unsafe: &unsafe
    TranslateText: libertymutual.score.unsafe
    ShortText: Unsafe
    <<: *red
  acceptable: &good
    TranslateText: libertymutual.score.good
    ShortText: Good
    <<: *light_green
  low: &fair
    TranslateText: libertymutual.score.fair
    ShortText: Fair
    <<: *orange
  medium: &poor
    TranslateText: libertymutual.score.poor
    ShortText: Poor
    <<: *red

ComponentValues:
  mal:
    "unsafe":
      Text: Unsafe {tableType} at all weights
      <<: *unsafe
    "acceptable":
      Text: Safe weight to {tableType}
      <<: *good
    "unacceptable":
      Text: Unsafe weight to {tableType}
      <<: *poor
  malSustained:
    "unsafe":
      Text: Unsafe {tableType} at all weights
      <<: *unsafe
    "acceptable":
      Text: Safe weight to {tableType}
      <<: *good
    "unacceptable":
      Text: Unsafe weight to {tableType}
      <<: *poor
  frequencyMultiplierLiftMale:
    "[None, 0]":
      <<: *unsafe
    "[0, 0.48]":
      <<: *poor
    "[0.48, 0.74]":
      <<: *fair
    "[0.74, 1]":
      <<: *good
    "[1, None]":
      <<: *good
  frequencyMultiplierLiftFemale:
    "[None, 0]":
      <<: *unsafe
    "[0, 0.6]":
      <<: *poor
    "[0.6, 0.8]":
      <<: *fair
    "[0.8, 1]":
      <<: *good
    "[1, None]":
      <<: *good
  verticalHeightMultiplierLiftMale:
    "[None, 0]":
      <<: *unsafe
    "[0, 0.85]":
      <<: *poor
    "[0.85, 0.93]":
      <<: *fair
    "[0.93, 1]":
      <<: *good
    "[1, None]":
      <<: *good
  verticalHeightMultiplierLiftFemale:
    "[None, 0]":
      <<: *unsafe
    "[0, 0.8]":
      <<: *poor
    "[0.8, 0.9]":
      <<: *fair
    "[0.9, 1]":
      <<: *good
    "[1, None]":
      <<: *good
  horizontalDistanceMultiplierLiftMale:
    "[None, 0]":
      <<: *unsafe
    "[0, 0.56]":
      <<: *poor
    "[0.56, 0.8]":
      <<: *fair
    "[0.8, 1.04]":
      <<: *good
    "[1.04, None]":
      <<: *good
  horizontalDistanceMultiplierLiftFemale:
    "[None, 0]":
      <<: *unsafe
    "[0, 0.58]":
      <<: *poor
    "[0.58, 0.79]":
      <<: *fair
    "[0.79, 1]":
      <<: *good
    "[1, None]":
      <<: *good
  frequencyMultiplierLowerMale:
    "[None, 0]":
      <<: *unsafe
    "[0, 0.51]":
      <<: *poor
    "[0.51, 0.75]":
      <<: *fair
    "[0.75, 1]":
      <<: *good
    "[1, None]":
      <<: *good
  frequencyMultiplierLowerFemale:
    "[None, 0]":
      <<: *unsafe
    "[0, 0.6]":
      <<: *poor
    "[0.6, 0.8]":
      <<: *fair
    "[0.8, 1]":
      <<: *good
    "[1, None]":
      <<: *good
  verticalHeightMultiplierLowerMale:
    "[None, 0]":
      <<: *unsafe
    "[0, 0.85]":
      <<: *poor
    "[0.85, 0.93]":
      <<: *fair
    "[0.93, 1]":
      <<: *good
    "[1, None]":
      <<: *good
  verticalHeightMultiplierLowerFemale:
    "[None, 0]":
      <<: *unsafe
    "[0, 0.8]":
      <<: *poor
    "[0.8, 0.9]":
      <<: *fair
    "[0.9, 1]":
      <<: *good
    "[1, None]":
      <<: *good
  horizontalDistanceMultiplierLowerMale:
    "[None, 0]":
      <<: *unsafe
    "[0, 0.56]":
      <<: *poor
    "[0.56, 0.8]":
      <<: *fair
    "[0.8, 1.04]":
      <<: *good
    "[1.04, None]":
      <<: *good
  horizontalDistanceMultiplierLowerFemale:
    "[None, 0]":
      <<: *unsafe
    "[0, 0.58]":
      <<: *poor
    "[0.58, 0.79]":
      <<: *fair
    "[0.79, 1]":
      <<: *good
    "[1, None]":
      <<: *good
  frequencyMultiplierPushMale:
    "[None, 0]":
      <<: *unsafe
    "[0, 0.63]":
      <<: *poor
    "[0.63, 0.81]":
      <<: *fair
    "[0.81, 1]":
      <<: *good
    "[1, None]":
      <<: *good
  frequencyMultiplierPushFemale:
    "[None, 0]":
      <<: *unsafe
    "[0, 0.68]":
      <<: *poor
    "[0.68, 0.84]":
      <<: *fair
    "[0.84, 1]":
      <<: *good
    "[1, None]":
      <<: *good
  verticalDistanceMultiplierPushMale:
    "[None, 0]":
      <<: *unsafe
    "[0, 0.97]":
      <<: *poor
    "[0.97, 0.99]":
      <<: *fair
    "[0.99, 1]":
      <<: *good
    "[1, None]":
      <<: *good
  verticalDistanceMultiplierPushFemale:
    "[None, 0]":
      <<: *unsafe
    "[0, 0.91]":
      <<: *poor
    "[0.91, 0.96]":
      <<: *fair
    "[0.96, 1]":
      <<: *good
    "[1, None]":
      <<: *good
  horizontalDistanceMultiplierPushMale:
    "[None, 0]":
      <<: *unsafe
    "[0, 0.76]":
      <<: *poor
    "[0.76, 0.88]":
      <<: *fair
    "[0.88, 1]":
      <<: *good
    "[1, None]":
      <<: *good
  horizontalDistanceMultiplierPushFemale:
    "[None, 0]":
      <<: *unsafe
    "[0, 0.71]":
      <<: *poor
    "[0.71, 0.85]":
      <<: *fair
    "[0.85, 1]":
      <<: *good
    "[1, None]":
      <<: *good
  frequencyMultiplierPullMale:
    "[None, 0]":
      <<: *unsafe
    "[0, 0.63]":
      <<: *poor
    "[0.63, 0.81]":
      <<: *fair
    "[0.81, 1]":
      <<: *good
    "[1, None]":
      <<: *good
  frequencyMultiplierPullFemale:
    "[None, 0]":
      <<: *unsafe
    "[0, 0.68]":
      <<: *poor
    "[0.68, 0.84]":
      <<: *fair
    "[0.84, 1]":
      <<: *good
    "[1, None]":
      <<: *good
  verticalDistanceMultiplierPullMale:
    "[None, 0]":
      <<: *unsafe
    "[0, 0.77]":
      <<: *poor
    "[0.77, 0.88]":
      <<: *fair
    "[0.88, 1]":
      <<: *good
    "[1, None]":
      <<: *good
  verticalDistanceMultiplierPullFemale:
    "[None, 0]":
      <<: *unsafe
    "[0, 0.91]":
      <<: *poor
    "[0.91, 0.96]":
      <<: *fair
    "[0.96, 1]":
      <<: *good
    "[1, None]":
      <<: *good
  horizontalDistanceMultiplierPullMale:
    "[None, 0]":
      <<: *unsafe
    "[0, 0.76]":
      <<: *poor
    "[0.76, 0.88]":
      <<: *fair
    "[0.88, 1]":
      <<: *good
    "[1, None]":
      <<: *good
  horizontalDistanceMultiplierPullFemale:
    "[None, 0]":
      <<: *unsafe
    "[0, 0.71]":
      <<: *poor
    "[0.71, 0.85]":
      <<: *fair
    "[0.85, 1]":
      <<: *good
    "[1, None]":
      <<: *good
  frequencyMultiplierCarryMale:
    "[None, 0]":
      <<: *unsafe
    "[0, 0.46]":
      <<: *poor
    "[0.46, 0.73]":
      <<: *fair
    "[0.73, 1]":
      <<: *good
    "[1, None]":
      <<: *good
  frequencyMultiplierCarryFemale:
    "[None, 0]":
      <<: *unsafe
    "[0, 0.65]":
      <<: *poor
    "[0.65, 0.83]":
      <<: *fair
    "[0.83, 1]":
      <<: *good
    "[1, None]":
      <<: *good
  verticalDistanceMultiplierCarryMale:
    "[None, 0]":
      <<: *unsafe
    "[0, 0.85]":
      <<: *poor
    "[0.85, 0.92]":
      <<: *fair
    "[0.92, 1]":
      <<: *good
    "[1, None]":
      <<: *good
  verticalDistanceMultiplierCarryFemale:
    "[None, 0]":
      <<: *unsafe
    "[0, 0.95]":
      <<: *poor
    "[0.95, 0.98]":
      <<: *fair
    "[0.98, 1]":
      <<: *good
    "[1, None]":
      <<: *good
  horizontalDistanceMultiplierCarryMale:
    "[None, 0]":
      <<: *unsafe
    "[0, 0.84]":
      <<: *poor
    "[0.84, 0.92]":
      <<: *fair
    "[0.92, 1]":
      <<: *good
    "[1, None]":
      <<: *good
  horizontalDistanceMultiplierCarryFemale:
    "[None, 0]":
      <<: *unsafe
    "[0, 0.97]":
      <<: *poor
    "[0.97, 0.99]":
      <<: *fair
    "[0.99, 1]":
      <<: *good
    "[1, None]":
      <<: *good

TableTypes:
  LIFT: 
    Number: 1
    Text: Lift
  LOWER:
    Number: 2
    Text: Lower
  PUSH:
    Number: 3
    Text: Push
  PULL:
    Number: 4
    Text: Pull
  CARRY:
    Number: 5
    Text: Carry
  "1": "LIFT"
  "2": "LOWER"
  "3": "PUSH"
  "4": "PULL"
  "5": "CARRY"

CouplingStatus:
  GOOD: 
    Number: 0
    Text: With handles
  POOR:
    Number: 1
    Text: Poor handles
  WITHOUT:
    Number: 2
    Text: Without handles

Units:
  STANDARD: 0
  METRIC: 1
