SeriaNumber: 9
Name: Mac
AssessmentName: MAC

Colors:
  black: &black
    rgba(15, 15, 30, 0.9)
  light_green: &light_green
    rgba(109, 208, 163, 1.0)
  green: &green
    rgba(241, 196, 15, 1.0)
  orange: &orange
    rgba(230, 126, 34, 1.0)
  red: &red
    rgba(184, 15, 10, 1.0)
  dark_red: &dark_red
    rgba(133, 4, 0, 1.0)

Constants:
  unacceptable: &unsafe
    Value: Unacceptable
    Color: *dark_red
  acceptable: &acceptable
    Value: Acceptable
    Color: *light_green
  low: &low
    Value: Low
    Color: *green
  medium: &medium
    Value: Medium
    Color: *orange
  high: &high
    Value: High
    Color: *red
  vhigh: &vhigh
    Value: Very High
    Color: *dark_red

Enum:
  InputId:
    1: 
      Value: Lift
      Label: Lifting operations
    2:
      Value: Carry
      Label: Carrying operations
    3:
      Value: Team
      Label: Team handling operations

OverallScoreValue: OverallScore

Metadata:
  startEnd: "{ [key: string]: number[] }"
  numPeople: "number"
  inputId: "number"

ResultValues:
  OverallScore:
    Label: Overall Score
    Values:
      "[None, None]":
        Label: Overall score
        Score: *acceptable
  LiftScore:
    Label: Lift Score
    Values:
      "[None, -0.0001]":
        Label: Unacceptable
        Score: *unsafe
      "[-0.0001, 5]":
        Label: Acceptable
        Score: *acceptable
      "[5, 10]":
        Label: Medium risk
        Score: *medium
      "[10, 15]":
        Label: High risk
        Score: *high
      "[15, None]":
        Label: Unacceptable
        Score: *unsafe
  CarryScore:
    Label: Carry Score
    Values:
      "[None, -0.0001]":
        Label: Unacceptable
        Score: *unsafe
      "[-0.0001, 5]":
        Label: Acceptable
        Score: *acceptable
      "[5, 10]":
        Label: Medium risk
        Score: *medium
      "[10, 15]":
        Label: High risk
        Score: *high
      "[15, None]":
        Label: Unacceptable
        Score: *unsafe
  TeamScore:
    Label: Team Score
    Values:
      "[None, -0.0001]":
        Label: Unacceptable
        Score: *unsafe
      "[-0.0001, 5]":
        Label: Acceptable
        Score: *acceptable
      "[5, 10]":
        Label: Medium risk
        Score: *medium
      "[10, 15]":
        Label: High risk
        Score: *high
      "[15, None]":
        Label: Unacceptable
        Score: *unsafe

RiskComponents:
  Lift:
    HandDistance: &handdistance
      Type: select
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Hand distance from the lower back
      Image: bodyParts/HandDistance.png
      Values:
        0:
          Label: Upper arms vertical and torso upright
          Desc: Hands close to the low back
          Score: *acceptable
        3:
          Label: Upper arms angled away from torso
          Desc: Hands at moderate distance from the low back
          Warning: High risk
          Score: *high
        3.1:
          Label: Torso bent forward
          Desc: Hands at moderate distance from the low back
          Warning: High risk
          Score: *high
        6:
          Label: Torso upright. Arms fully outstretched
          Desc: Hands far from the low back
          Warning: Very high risk
          Score: *vhigh
        6.1:
          Label: Upper arms angled away from torso and torso bent forward
          Desc: Hands far from the low back
          Warning: Very high risk
          Score: *vhigh
    VerticalLiftZones: &verticalliftzones
      Type: select
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Vertical lift zones
      Image: bodyParts/VerticalLiftZones.png
      Values:
        0:
          Label: Hands between knee and elbow height
          Score: *acceptable
        1:
          Label: Hands between knee and floor level
          Warning: Low risk
          Score: *low
        1.1:
          Label: Hands between elbow height and head height
          Warning: Low risk
          Score: *low
        3:
          Label: Hands at floor level or below
          Warning: High risk
          Score: *high
        3.1:
          Label: Hands at head height or above
          Warning: High risk
          Score: *high
    TorsoTwisting: &torsotwisting
      Type: select
      Base: 0
      MaxInput: ~
      Units: angle
      Label: Torso twisting and sideways bending
      Image: bodyParts/TorsoTwisting.png
      Values:
        0:
          Label: Little or no torso twisting or sideways bending
          Score: *acceptable
        1:
          Label: Torso twisted
          Warning: Low risk
          Score: *low
        1.1:
          Label: Torso bent sideways
          Warning: Low risk
          Score: *low
        2:
          Label: Torso both twisted and bent sideways
          Warning: Medium risk
          Score: *medium
  Carry:
    HandDistance: *handdistance
    CarryDistance: &carrydistance
      Type: select
      Base: 0
      MaxInput: ~
      Units: [ft, m]
      Label: Carry distance
      Image: additionalInputs/CarryDistance.png
      Values:
        0:
          Label: Between 2 m and 4 m
          Score: *acceptable
        1:
          Label: Between 4 m and 10 m
          Warning: Low risk
          Score: *low
        2:
          Label: Over 10 m
          Warning: Medium risk
          Score: *medium
  Team:
    HandDistance:
      Type: select
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Hand distance from the lower back
      Image: bodyParts/HandDistance.png
      Values:
        0:
          Label: Upper arms vertical and torso upright
          Desc: Hands close to the low back
          Score: *acceptable
        3:
          Label: Upper arms angled away from torso or torso bent forward
          Desc: Hands at moderate distance from the low back
          Warning: High risk
          Score: *high
        6:
          Label: Upper arms angled away from torso and torso bent forward
          Desc: Hands far from the low back
          Warning: Very high risk
          Score: *vhigh
    VerticalLiftZones: &verticalliftzones
      Type: select
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Vertical lift zones
      Image: bodyParts/VerticalLiftZones.png
      Values:
        0:
          Label: Hands between knee and elbow height
          Score: *acceptable
        1:
          Label: Hands below knee and/or above elbow height
          Warning: Low risk
          Score: *low
        3:
          Label: Hands at floor level or below or head height and above
          Warning: High risk
          Score: *high
    TorsoTwisting:
      Type: select
      Base: 0
      MaxInput: ~
      Units: angle
      Label: Torso twisting and sideways bending
      Image: bodyParts/TorsoTwisting.png
      Values:
        0:
          Label: Little or no torso twisting or sideways bending
          Score: *acceptable
        1:
          Label: Torsos either twisted or bent sideways
          Warning: Low risk
          Score: *low
        2:
          Label: Torsos both twisted and bent sideways
          Warning: Medium risk
          Score: *medium
    CarryDistance:
      <<: *carrydistance
      Values:
        0:
          Label: Between 2 m and 4 m
          Score: *acceptable
        1:
          Label: Between 4 m and 10 m
          Warning: Low risk
          Score: *low
        3:
          Label: Over 10 m
          Warning: Medium risk
          Score: *medium

AdditionalInputs:
  Lift:
    LoadWeight: &loadweight
      Type: input
      Base: 1
      MaxInput: 100
      Units: [lbs, kgs]
      Label: Object Weight
      Image: additionalInputs/ForceLoad.png
      Values: ~
    Frequency: &frequency
      Type: input
      Base: 1
      MaxInput: 100
      Units: per hour
      Label: Frequency
      Image: additionalInputs/Frequency.png
      Values: ~
    PosturalConstraints: &posturalconstraints
      Type: select
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Postural constraints
      Image: additionalInputs/PosturalConstraints.png
      Values:
        0:
          Label: No postural constraints
          Score: *acceptable
        1:
          Label: Restricted posture
          Warning: Low risk
          Score: *low
        3:
          Label: Severely restricted
          Warning: High risk
          Score: *high
    GripOnLoad: &griponload
      Type: select
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Grip on load
      Image: additionalInputs/Coupling.png
      Values:
        0:
          Label: Good grip
          Desc: Fit-for-purpose handles/ handholds matched to the size and weight of the load
          Score: *acceptable
        0.1:
          Label: Cylindrical handles or items the whole hand can wrap round comfortably
          Score: *acceptable
        1:
          Label: Handles or handholds too small or lack finger clearance or only the fingers support the load
          Warning: Reasonable grip
          Score: *low
        1.1:
          Label: No handles or handholds but can be held underneath, or has strap or loop handles
          Warning: Reasonable grip
          Score: *low
        2:
          Label: No handles or handhold areas
          Warning: Poor grip
          Score: *medium
        2.1:
          Label: Palm, pinch or fingertip grip or force used to keep items together
          Warning: Poor grip
          Score: *medium
        2.2:
          Label: Rough, slippery or with pressure points
          Warning: Poor grip
          Score: *medium
        2.3:
          Label: Irregular, bulky or non-rigid
          Warning: Poor grip
          Score: *medium
    FloorSurface: &floorsurface
      Type: select
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Floor surface
      Image: additionalInputs/Floor.png
      Values:
        0:
          Label: Non-slip, dry, clean, firm, level and undamaged
          Score: *acceptable
        1:
          Label: Mostly dry and clean (damp or some debris), or reasonably
          Warning: Reasonable floor surface
          Score: *low
        2:
          Label: Slippery (greasy, oily, wet, icy) or much debris or soft or unstable or severe damage
          Warning: Poor floor surface
          Score: *medium
    EnvironmentalFactors: &environmentalfactors
      Type: select
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Environmental factors
      Image: additionalInputs/Environment.png
      Values:
        0:
          Label: No factors
          Score: *acceptable
        1:
          Label: One factor
          Warning: Low risk
          Score: *low
        2:
          Label: Two or more factors
          Warning: Medium risk
          Score: *medium
  Carry:
    LoadWeight: *loadweight
    Frequency: *frequency
    AsymmetricalTorso: &asymmetricaltorso
      Type: select
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Asymmetrical torso or load
      Image: additionalInputs/AssymetricalTorso.png
      Values:
        0:
          Label: Load and hands symmetrical in front of the torso
          Score: *acceptable
        1:
          Label: Torso symmetrical but load is carried to one side
          Warning: Low risk
          Score: *low
        1.1:
          Label: Load not symmetrical
          Warning: Low risk
          Score: *low
        2:
          Label: Two-handed carrying to the side
          Warning: Medium risk
          Score: *medium
    PosturalConstraints: *posturalconstraints
    GripOnLoad: *griponload
    FloorSurface: &floorsurface2
      <<: *floorsurface
      Values:
        0:
          Label: Non-slip, dry, clean, firm, level and undamaged
          Score: *acceptable
        1:
          Label: Mostly dry and clean (damp or some debris), or reasonably
          Warning: Reasonable floor surface
          Score: *low
        3:
          Label: Slippery (greasy, oily, wet, icy) or much debris or soft or unstable or severe damage
          Warning: Poor floor surface
          Score: *high
    Obstacles: &obstacles
      Type: select
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Obstacles on route
      Image: additionalInputs/Obstacles.png
      Values:
        0:
          Label: No obstacles and carry route flat or slopes gently
          Score: *acceptable
        2:
          Label: One type of obstacle or steep slope
          Warning: Medium risk
          Score: *medium
        3:
          Label: Ladders or at least two types of obstacle
          Warning: High risk
          Score: *high
    EnvironmentalFactors: *environmentalfactors
  Team:
    LoadWeight:
      Type: select
      Base: 0
      MaxInput: ~
      Units: [lbs, kgs]
      Label: Load weight
      Image: additionalInputs/AverageLoad.png
      Values:
        0:
          Label: 2 people < 35 kg, 3 people < 55 kg, 4 people < 75 kg
          Score: *acceptable
        4:
          Label: 2 people 35–65 kg, 3 people 55–95 kg, 4 people 75–130 kg
          Warning: Medium risk
          Score: *medium
        6:
          Label: 2 people 65–85 kg, 3 people 95–130 kg, 4 people 130–170 kg
          Warning: High risk
          Score: *high
        10:
          Label: Ladders or at least two types of obstacle
          Warning: Very high risk
          Score: *vhigh
    PosturalConstraints: *posturalconstraints
    GripOnLoad:
      <<: *griponload
      Values:
        0:
          Label: Good grip
          Desc: Fit-for-purpose handles/ handholds matched to the size and weight of the load
          Score: *acceptable
        0.1:
          Label: Cylindrical handles or items the whole hand can wrap round comfortably
          Score: *acceptable
        2:
          Label: Handles or handholds too small or lack finger clearance or only the fingers support the load
          Warning: Reasonable grip
          Score: *low
        2.1:
          Label: No handles or handholds but can be held underneath, or has strap or loop handles
          Warning: Reasonable grip
          Score: *low
        4:
          Label: No handles or handhold areas
          Warning: Poor grip
          Score: *medium
        4.1:
          Label: Palm, pinch or fingertip grip or force used to keep items together
          Warning: Poor grip
          Score: *medium
        4.2:
          Label: Rough, slippery or with pressure points
          Warning: Poor grip
          Score: *medium
        4.3:
          Label: Irregular, bulky or non-rigid
          Warning: Poor grip
          Score: *medium
    FloorSurface: *floorsurface2
    Obstacles: *obstacles
    Communication:
      Type: select
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Communication, co-ordination and control
      Image: additionalInputs/Communication.png
      Values:
        0:
          Label: Good communication, co-ordination and control
          Score: *acceptable
        1:
          Label: Reasonable communication, co-ordination and control
          Warning: Medium risk
          Score: *low
        3:
          Label: Poor communication co-ordination and control
          Warning: High risk
          Score: *high
    EnvironmentalFactors: *environmentalfactors

Form:
  RiskComponents:
    Groups:
      0:
        Label: ~
        Inline: False
    Items:
      1:
        Input: Lift
        Component: HandDistance
        Group: "0"
      2:
        Input: Lift
        Component: VerticalLiftZones
        Group: "0"
      3:
        Input: Lift
        Component: TorsoTwisting
        Group: "0"
      4:
        Input: Carry
        Component: HandDistance
        Group: "0"
      5:
        Input: Carry
        Component: CarryDistance
        Group: "0"
      6:
        Input: Team
        Component: HandDistance
        Group: "0"
      7:
        Input: Team
        Component: VerticalLiftZones
        Group: "0"
      8:
        Input: Team
        Component: TorsoTwisting
        Group: "0"
      9:
        Input: Team
        Component: CarryDistance
        Group: "0"
  AdditionalInputs:
    Groups:
      0:
        Label: ~
        Inline: False
    Items:
      0:
        Input: Lift
        Component: LoadWeight
        Group: "0"
      1:
        Input: Lift
        Component: Frequency
        Group: "0"
      2:
        Input: Lift
        Component: PosturalConstraints
        Group: "0"
      3:
        Input: Lift
        Component: GripOnLoad
        Group: "0"
      4:
        Input: Lift
        Component: FloorSurface
        Group: "0"
      5:
        Input: Lift
        Component: EnvironmentalFactors
        Group: "0"
      6:
        Input: Carry
        Component: LoadWeight
        Group: "0"
      7:
        Input: Carry
        Component: Frequency
        Group: "0"
      8:
        Input: Carry
        Component: AsymmetricalTorso
        Group: "0"
      9:
        Input: Carry
        Component: PosturalConstraints
        Group: "0"
      10:
        Input: Carry
        Component: GripOnLoad
        Group: "0"
      11:
        Input: Carry
        Component: FloorSurface
        Group: "0"
      12:
        Input: Carry
        Component: Obstacles
        Group: "0"
      13:
        Input: Carry
        Component: EnvironmentalFactors
        Group: "0"
      14:
        Input: Team
        Component: LoadWeight
        Group: "0"
      15:
        Input: Team
        Component: PosturalConstraints
        Group: "0"
      16:
        Input: Team
        Component: GripOnLoad
        Group: "0"
      17:
        Input: Team
        Component: FloorSurface
        Group: "0"
      18:
        Input: Team
        Component: Obstacles
        Group: "0"
      19:
        Input: Team
        Component: Communication
        Group: "0"
      20:
        Input: Team
        Component: EnvironmentalFactors
        Group: "0"
  Results:
    Groups:
      0:
        Label: ~
        Type: riskscore
    Items:
      0:
        Input: Lift
        Component: LiftScore
        Group: "0"
        Label: MSD risk score
      1:
        Input: Carry
        Component: CarryScore
        Group: "0"
        Label: MSD risk score
      2:
        Input: Team
        Component: TeamScore
        Group: "0"
        Label: MSD risk score
  CanGenerate:
    Report: true
    Worksheet: true
    Powerpoint: true
    Csv: true
    AIRecommendations: true
    Project: true
