SeriaNumber: 3
Name: Niosh
AssessmentName: NIOSH

Colors:
  black: &black
    rgba(15, 15, 30, 0.9)

  light_green: &light_green
    rgba(109, 208, 163, 1.0)

  green: &green
    rgba(20, 210, 184, 1.0)

  orange: &orange
    rgba(234, 130, 130, 1.0)

  red: &red
    rgba(184, 15, 10, 1.0)

Constants:
  SAMPLE_SIZE_SECONDS:
    Value: .5

  FM_FREQUENCIES:
    Value: [0, .2, .5, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

  FM_SHORT_DURATION:
    Value:
      [
        1.0,
        1.0,
        .97,
        .94,
        .91,
        .88,
        .84,
        .80,
        .75,
        .70,
        .60,
        .52,
        .45,
        .41,
        .37,
        .34,
        .31,
        .28,
      ]

  FM_MODERATE_DURATION:
    Value:
      [
        .95,
        .95,
        .92,
        .88,
        .84,
        .79,
        .72,
        .60,
        .50,
        .42,
        .35,
        .30,
        .26,
        .23,
        .21,
        0,
        0,
        0,
      ]

  FM_LONG_DURATION:
    Value:
      [
        .85,
        .85,
        .81,
        .75,
        .65,
        .55,
        .45,
        .35,
        .27,
        .22,
        .18,
        .15,
        .13,
        0,
        0,
        0,
        0,
        0,
      ]

  FM_SHORT_DURATION_VERTICAL_CUTOFF:
    Value: 13

  FM_MODERATE_DURATION_VERTICAL_CUTOFF:
    Value: 10

  FM_LONG_DURATION_VERTICAL_CUTOFF:
    Value: 8

  unsafe: &unsafe
    Value: Unsafe
    Color: *red

  acceptable: &acceptable
    Value: Good
    Color: *light_green

  low: &low
    Value: Fair
    Color: *orange

  medium: &medium
    Value: Poor
    Color: *red

Enum:
  CouplingStatus:
    GOOD:
      Value: 0
      Label: Good
    FAIR:
      Value: 1
      Label: Fair
    POOR:
      Value: 2
      Label: Poor

  DurationStatus:
    SHORT:
      Value: 0
      Label: Short (1 hour)
    MODERATE:
      Value: 1
      Label: Moderate (1 - 2 hours)
    LONG:
      Value: 2
      Label: Long (2 - 8 hours)

OverallScoreValue: li

Metadata:
  numLifts: "number"
  subjectHeight: "number"
  startEnd: "{ [key: string]: number[] }"

ResultValues:
  li:
    "[None, 0]":
      Label: Unsafe lift at all weights
      Score: *unsafe
    "[0, 1]":
      Label: Safe weight to lift
      Score: *acceptable
    "[1, 3]":
      Label: Medium risk
      Warning: Object heavy
      Score: *low
    "[3, None]":
      Label: High risk
      Warning: Object far too heavy
      Score: *medium
  
  hm:
    "[0, .4]":
      Label: Poor
      Warning: Object too far away horizontally
      Score: *medium
    "[.4, .6]":
      Label: Fair
      Warning: Object too far away horizontally
      Score: *low
    "[.6, None]":
      Label: Good
      Score: *acceptable
  
  vm:
    "[0, .8]":
      Label: Poor
      Warning: Object begins too far away vertically
      Score: *medium
    "[.8, .9]":
      Label: Fair
      Score: *low
    "[.9, None]":
      Label: Good
      Score: *acceptable
  
  dm:
    "[0, .9]":
      Label: Poor
      Warning: Object travels too far
      Score: *medium
    "[.9, .95]":
      Label: Fair
      Score: *low
    "[.95, None]":
      Label: Good
      Score: *acceptable
  
  am:
    "[0, .7]":
      Label: Poor
      Warning: Person twists too much
      Score: *medium
    "[.7, .9]":
      Label: Fair
      Score: *low
    "[.9, None]":
      Label: Good
      Score: *acceptable
  
  fm:
    "[0, .45]":
      Label: Poor
      Warning: Intervals too short
      Score: *medium
    "[.45, .8]":
      Label: Fair
      Score: *low
    "[.8, None]":
      Label: Good
      Score: *acceptable
  
  rwl:
    "[-1000, 10000]":
      Label: Recommended Weight Limit
      Score: *acceptable

RiskComponents:
  0:
    asymmetryAngle:
      Type: input
      Base: 0
      MaxInput: 135
      Units: deg
      Label: Asymmetry Angle
      Image: bodyParts/asymmetryAngle.png
      Values: ~
    horizontalEnd:
      Type: input
      Base: 0.83
      MaxInput: 5.83333
      Units: [ft, m]
      Label: Horizontal End
      Image: bodyParts/horizontalEnd.png
      Values: ~
    horizontalStart:
      Type: input
      Base: 0.83
      MaxInput: 2.08
      Units: [ft, m]
      Label: Horizontal Start
      Image: bodyParts/horizontalStart.png
      Values: ~
    verticalEnd:
      Type: input
      Base: 0.83
      MaxInput: 5.83333
      Units: [ft, m]
      Label: Vertical End
      Image: bodyParts/verticalEnd.png
      Values: ~
    verticalStart:
      Type: input
      Base: 0.83
      MaxInput: 5.83333
      Units: [ft, m]
      Label: Vertical Start
      Image: bodyParts/verticalStart.png
      Values: ~

AdditionalInputs:
  Main:
    averageLoad:
      Type: input
      Base: 0.01
      MaxInput: 60
      Units: [lbs, kgs]
      Label: Average Load
      Image: additionalInputs/AverageLoad.png
      Values: ~
    frequency:
      Type: input
      Base: 1
      MaxInput: 15
      Units: min
      Label: Frequency
      Image: additionalInputs/Frequency.png
      Values: ~
    coupling:
      Type: select
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Coupling
      Image: additionalInputs/Coupling.png
      Values:
        0:
          Label: Good
          Score: *acceptable
        1:
          Label: Fair
          Score: *low
        2:
          Label: Poor
          Warning: Poor coupling
          Score: *medium
    liftingDuration:
      Type: select
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Lifting Duration
      Image: additionalInputs/LiftingDuration.png
      Values:
        0:
          Label: Short (1 hour)
          Score: *acceptable
        1:
          Label: Moderate (1-2 hours)
          Score: *low
        2:
          Label: Long (2-8 hours)
          Warning: Long lifting duration
          Score: *medium
    loadConstant:
      Type: input
      Base: 51
      MaxInput: 1000
      Units: ~
      Label: Load Constant
      Image: ~
      Values: ~
    shortRest:
      Type: input
      Base: -1
      MaxInput: 100
      Units: ~
      Label: Short rest
      Image: ~
      Values: ~
      IsOptional: True