---
constants:
  light_green: &light_green
    Color:
      rgba(109, 208, 163, 1.0)

  green: &green
    Color:
      rgba(241, 196, 15, 1.0)

  orange: &orange
    Color:
      rgba(230, 126, 34, 1.0)

  red: &red
    Color:
      rgba(184, 15, 10, 1.0)

  dark_red: &dark_red
    Color:
      rgba(133, 4, 0, 1.0)

  acceptable: &acceptable
    TranslateText: rulareba.score.acceptable
    ShortText: Acceptable
    Text: Acceptable
    <<: *light_green
  low: &low
    TranslateText: rulareba.score.low
    ShortText: Low
    Text: Low risk of injury
    <<: *green
  medium: &medium
    TranslateText: rulareba.score.medium
    ShortText: Medium
    Text: Medium risk of injury
    <<: *orange
  high: &high
    TranslateText: rulareba.score.high
    ShortText: High
    Text: High risk of injury
    <<: *red
  vhigh: &vhigh
    TranslateText: rulareba.score.vhigh
    ShortText: Very High
    Text: Very high risk of injury
    <<: *dark_red

Colors:
  acceptable: *light_green
  low: *green
  medium: *orange
  high: *red
  vhigh: *dark_red

BodyPartScores:
  Overall:
    1:
      << : *acceptable
    2:
      << : *low
    3:
      << : *low
    4:
      << : *medium
    5: 
      << : *medium
    6:
      << : *medium
    7:
      << : *medium
    8:
      << : *high
    9:
      << : *high
    10:
      << : *high
    11:
      << : *vhigh
    12:
      << : *vhigh
    13:
      << : *vhigh
    14:
      << : *vhigh
    15:
      << : *vhigh
    16:
      << : *vhigh
  Neck:
    1:
      << : *acceptable
    2:
      << : *low
    3: 
      << : *medium
    4: 
      << : *medium
    5: 
      << : *high
    6:
      << : *high
  Upper Arm:
    1:
      << : *acceptable 
    2:
      << : *low
    3: 
      << : *medium
    4: 
      << : *medium
    5: 
      << : *high
    6:
      << : *high
  Lower Arm:
    1:
      << : *acceptable
    2:
      << : *medium
  Trunk:
    1:
      << : *acceptable
    2:
      << : *low
    3: 
      << : *medium
    4: 
      << : *medium
    5: 
      << : *high
    6:
      << : *high
  Leg:
    1:
      << : *acceptable
    2:
      << : *low
    3: 
      << : *medium
    4: 
      << : *high
  Wrist:
    1:
      << : *acceptable
    2:
      << : *medium
    3:
      << : *high

ComponentValues:
  Neck:
    Score:
      1:
        Text: 0° - 20° forward
        Warning: ~
        Image: angleIcons/rulaReba/Neck_0_20_deg@2x.png
      2:
        Text: 20°+ forward/backward
        Warning: Neck bent
        Image: angleIcons/rulaReba/Neck_20+_deg@2x.png
        Image2: angleIcons/rulaReba/Neck_in_extension@2x.png
      Base: 1
      type: select
      label: Angle
    SideBend:
      1:
        Text: Yes
        Warning: Neck side bending
      0:
        Text: No
        Warning: ~
      label: Side bending
      type: boolean
      Base: 0
      Image: angleIcons/rulaReba/Neck_side_bending@2x.png
    Twist:
      1:
        Text: Yes
        Warning: Neck twisted
      0:
        Text: No
        Warning: 
      label: Twisted
      type: boolean
      Base: 0
      Image: angleIcons/rulaReba/Neck_Twisted@2x.png
    Image: 'bodyParts/neck.png'

  Upper Arm:
    Score:
      1:
        Text: 20° in front - 20° behind
        Warning: ~
        Image: angleIcons/rulaReba/UpperArm_20_20_deg@2x.png
      2:
        Text: 20°+ behind OR 20° - 45° in front
        Warning: Upper arm bent slightly
        Image: angleIcons/rulaReba/UpperArm_20_deg_extension@2x.png
        Image2: angleIcons/rulaReba/UpperArm_20_45_deg@2x.png
      3:
        Text: 45° - 90° in front
        Warning: Upper arm bent forward
        Image: angleIcons/rulaReba/UpperArm_45_90_deg@2x.png
      4:
        Text: 90°+ in front
        Warning: Upper arm bent very forward
        Image: angleIcons/rulaReba/UpperArm_90+_deg@2x.png
      Base: 1
      label: Angle
      TranslateLabel: rulareba.upperarm.score
      type: select
    Abducted:
      1:
        Text: Yes
        Warning: Shoulder abducted
      0:
        Text: No
        Warning: ~
      Base: 0
      label: Abducted
      TranslateLabel: rulareba.upperarm.abducted
      type: boolean
      Image: angleIcons/rulaReba/UpperArm_abducted@2x.png
    ShoulderRaised:
      1:
        Text: Yes
        Warning: Shoulders raised
      0:
        Text: No
        Warning: 
      Base: 0
      label: Shoulder raised
      TranslateLabel: rulareba.upperarm.shoulder_raised
      type: boolean
      Image: angleIcons/rulaReba/UpperArm_shoulder_raised@2x.png
    Image: 'bodyParts/shoulder.png'

  Trunk:
    Score:
      1:
        Text: 0°
        Warning: ~
        Image: angleIcons/rulaReba/Trunk_0_deg@2x.png
      2:
        Text: 0° - 20° forward
        Warning: ~
        Image: angleIcons/rulaReba/Trunk_0_20_deg@2x.png
      3:
        Text: 20° - 60° forward
        Warning: Trunk bent forward too much
        Image: angleIcons/rulaReba/Trunk_20_60_deg@2x.png
      4:
        Text: 60°+ forward
        Warning: Trunk bent forward too much
        Image: angleIcons/rulaReba/Trunk_60+_deg@2x.png
      label: Angle
      TranslateLabel: rulareba.trunk.score
      type: select
      Base: 1
    SideBend:
      1:
        Text: Yes
        Warning: Trunk side bending
      0:
        Text: No
        Warning: 
      Base: 0
      label: Side bending
      TranslateLabel: rulareba.trunk.sidebend
      type: boolean
      Image: angleIcons/rulaReba/Trunk_side_bending@2x.png
    Twist:
      1:
        Text: Yes
        Warning: Trunk twisted
      0:
        Text: No
        Warning: ~
      label: Twisted
      type: boolean
      TranslateLabel: rulareba.trunk.twist
      Base: 0
      Image: angleIcons/rulaReba/Trunk_Twisted@2x.png
    Image: 'bodyParts/back.png'
  Lower Arm:
    Score:
      1:
        Text: 60° - 100°
        Warning: ~
        Image: angleIcons/rulaReba/LowerArm_60_100_deg@2x.png
      2:
        Text: 0° - 60° OR 100°+
        Warning: Lower arm not in neutral 90° position
        Image: angleIcons/rulaReba/LowerArm_0_60_deg@2x.png
        Image2: angleIcons/rulaReba/LowerArm_100+_deg@2x.png
      label: Angle
      type: select
      TranslateLabel: rulareba.lower_arm.score
      Base: 1
    Image: 'bodyParts/arm.png'
  Wrist:
    Score:
      1:
        Text: 15° up - 15° down
        Warning:
        Image: angleIcons/rulaReba/Wrist_15_15_Deg@2x.png
      2:
        Text: 15°+ up OR 15°+ down
        Warning: Wrist far too bent
        Image: angleIcons/rulaReba/Wrist_15+Up_Deg@2x.png
        Image2: angleIcons/rulaReba/Wrist_15+Down_Deg@2x.png
      label: Angle
      type: select
      TranslateLabel: rulareba.wrist.score
      Base: 1
    Twist:
      1:
        Text: Yes
        TranslateText: rulareba.yes
        TranslateWarning: ~
        Warning: ~
      0:
        Text: No
        TranslateText: rulareba.no
        TranslateWarning: ~
        Warning: ~
      Base: 0
      type: boolean
      label: Twisted
      TranslateLabel: rulareba.wrist.twist
      Image: angleIcons/rulaReba/Wrist_twisted_palm_down@2x.png
      Image2: angleIcons/rulaReba/Wrist_twisted_palm_up@2x.png
    Image: 'bodyParts/wrist.png'

  Leg:
    Score:
      1:
        Text: 0
        Warning: ~
        Image: angleIcons/rulaReba/Leg_both_down@2x.png
      2:
        Text: 30° - 60°
        Warning: ~
        Image: angleIcons/rulaReba/Leg_30_60_Deg@2x.png
      3:
        Text: 60°+
        Warning: Legs bent too much
        Image: angleIcons/rulaReba/Leg_60+_deg@2x.png
      label: Angle
      type: select
      TranslateLabel: rulareba.leg.score
      Base: 1
    UnstableFooting:
      1:
        Text: Yes
        Warning: ~
      0:
        Text: No
        Warning: ~
      label: Feet crossed or otherwise unstable on ground
      type: boolean
      Base: 0
      Image: angleIcons/rulaReba/Leg_one_raised@2x.png
    Image: 'bodyParts/leg.png'
    
...