SeriaNumber: 2
Name: Reba
AssessmentName: REBA

Colors:
  light_green: &light_green
    rgba(109, 208, 163, 1.0)

  green: &green
    rgba(241, 196, 15, 1.0)

  orange: &orange
    rgba(230, 126, 34, 1.0)

  red: &red
    rgba(184, 15, 10, 1.0)

  dark_red: &dark_red
    rgba(133, 4, 0, 1.0)

Constants:
  acceptable: &acceptable
    Value: Acceptable
    Color: *light_green

  low: &low
    Value: Low
    Color: *green

  medium: &medium
    Value: Medium
    Color: *orange

  high: &high
    Value: High
    Color: *red

  vhigh: &vhigh
    Value: Very High
    Color: *dark_red

Enum: {}

OverallScoreValue: Overall

Metadata: {}

ResultValues:
  Overall:
    Label: Overall Score
    Values:
      1:
        Label: Acceptable
        Score: *acceptable
      2:
        Label: Low
        Score: *low
      3:
        Label: Low
        Score: *low
      4:
        Label: Medium
        Score: *medium
      5:
        Label: Medium
        Score: *medium
      6:
        Label: Medium
        Score: *medium
      7:
        Label: Medium
        Score: *medium
      8:
        Label: High
        Score: *high
      9:
        Label: High
        Score: *high
      10:
        Label: High
        Score: *high
      11:
        Label: Very High
        Score: *vhigh
      12:
        Label: Very High
        Score: *vhigh
      13:
        Label: Very High
        Score: *vhigh
      14:
        Label: Very High
        Score: *vhigh
      15:
        Label: Very High
        Score: *vhigh
      16:
        Label: Very High
        Score: *vhigh

  Neck:
    Label: Neck
    Values:
      1:
        Label: Acceptable
        Score: *acceptable
      2:
        Label: Low
        Score: *low
      3:
        Label: Medium
        Score: *medium
      4:
        Label: Medium
        Score: *medium
      5:
        Label: High
        Score: *high
      6:
        Label: High
        Score: *high

  Upper Arm:
    Label: Upper Arm
    Values:
      1:
        Label: Acceptable
        Score: *acceptable
      2:
        Label: Low
        Score: *low
      3:
        Label: Medium
        Score: *medium
      4:
        Label: Medium
        Score: *medium
      5:
        Label: High
        Score: *high
      6:
        Label: High
        Score: *high

  Lower Arm:
    Label: Lower Arm
    Values:
      1:
        Label: Acceptable
        Score: *acceptable
      2:
        Label: Medium
        Score: *medium

  Trunk:
    Label: Trunk
    Values:
      1:
        Label: Acceptable
        Score: *acceptable
      2:
        Label: Low
        Score: *low
      3:
        Label: Medium
        Score: *medium
      4:
        Label: Medium
        Score: *medium
      5:
        Label: High
        Score: *high
      6:
        Label: High
        Score: *high

  Leg:
    Label: Leg
    Values:
      1:
        Label: Acceptable
        Score: *acceptable
      2:
        Label: Low
        Score: *low
      3:
        Label: Medium
        Score: *medium
      4:
        Label: High
        Score: *high

  Wrist:
    Label: Wrist
    Values:
      1:
        Label: Acceptable
        Score: *acceptable
      2:
        Label: Medium
        Score: *medium
      3:
        Label: High
        Score: *high

RiskComponents:
  Neck:
    Score:
      Type: imageSelect
      Base: 1
      MaxInput: ~
      Units: ~
      Label: Angle
      Image: bodyParts/neck.png
      Values:
        1:
          Label: 0° - 20° forward
          Image: angleIcons/rulaReba/Neck_0_20_deg@2x.png
        2:
          Label: 20°+ forward/backward
          Image: angleIcons/rulaReba/Neck_20+_deg@2x.png
          Image2: angleIcons/rulaReba/Neck_in_extension@2x.png
          Warning: Neck bent
    SideBend:
      Type: checkbox
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Side bending
      Image: ~
      Values:
        1:
          Label: Yes
          Image: angleIcons/rulaReba/Neck_side_bending@2x.png
          Warning: Neck side bending
        0:
          Label: No
    Twist:
      Type: checkbox
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Twisted
      Image: ~
      Values:
        1:
          Label: Yes
          Image: angleIcons/rulaReba/Neck_Twisted@2x.png
          Warning: Neck twisted
        0:
          Label: No

  Upper Arm:
    Score:
      Type: imageSelect
      Base: 1
      MaxInput: ~
      Units: ~
      Label: Angle
      Image: bodyParts/shoulder.png
      Values:
        1:
          Label: 20° in front - 20° behind
          Image: angleIcons/rulaReba/UpperArm_20_20_deg@2x.png
        2:
          Label: 20°+ behind OR 20° - 45° in front
          Image: angleIcons/rulaReba/UpperArm_20_deg_extension@2x.png
          Image2: angleIcons/rulaReba/UpperArm_20_45_deg@2x.png
          Warning: Upper arm bent slightly
        3:
          Label: 45° - 90° in front
          Image: angleIcons/rulaReba/UpperArm_45_90_deg@2x.png
          Warning: Upper arm bent forward
        4:
          Label: 90°+ in front
          Image: angleIcons/rulaReba/UpperArm_90+_deg@2x.png
          Warning: Upper arm bent very forward
    Abducted:
      Type: checkbox
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Abducted
      Image: ~
      Values:
        1:
          Label: Yes
          Image: angleIcons/rulaReba/UpperArm_abducted@2x.png
          Warning: Shoulder abducted
        0:
          Label: No
    ShoulderRaised:
      Type: checkbox
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Shoulder raised
      Image: ~
      Values:
        1:
          Label: Yes
          Image: angleIcons/rulaReba/UpperArm_shoulder_raised@2x.png
          Warning: Shoulders raised
        0:
          Label: No

  Trunk:
    Score:
      Type: imageSelect
      Base: 1
      MaxInput: ~
      Units: ~
      Label: Angle
      Image: bodyParts/back.png
      Values:
        1:
          Label: 0°
          Image: angleIcons/rulaReba/Trunk_0_deg@2x.png
        2:
          Label: 0° - 20° forward
          Image: angleIcons/rulaReba/Trunk_0_20_deg@2x.png
        3:
          Label: 20° - 60° forward
          Image: angleIcons/rulaReba/Trunk_20_60_deg@2x.png
          Warning: Trunk bent forward too much
        4:
          Label: 60°+ forward
          Image: angleIcons/rulaReba/Trunk_60+_deg@2x.png
          Warning: Trunk bent forward too much
    SideBend:
      Type: checkbox
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Side bending
      Image: ~
      Values:
        1:
          Label: Yes
          Image: angleIcons/rulaReba/Trunk_side_bending@2x.png
          Warning: Trunk side bending
        0:
          Label: No
    Twist:
      Type: checkbox
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Twisted
      Image: ~
      Values:
        1:
          Label: Yes
          Image: angleIcons/rulaReba/Trunk_Twisted@2x.png
          Warning: Trunk twisted
        0:
          Label: No

  Lower Arm:
    Score:
      Type: imageSelect
      Base: 1
      MaxInput: ~
      Units: ~
      Label: Angle
      Image: bodyParts/arm.png
      Values:
        1:
          Label: 60° - 100°
          Image: angleIcons/rulaReba/LowerArm_60_100_deg@2x.png
        2:
          Label: 0° - 60° OR 100°+
          Image: angleIcons/rulaReba/LowerArm_0_60_deg@2x.png
          Image2: angleIcons/rulaReba/LowerArm_100+_deg@2x.png
          Warning: Lower arm not in neutral 90° position

  Wrist:
    Score:
      Type: imageSelect
      Base: 1
      MaxInput: ~
      Units: ~
      Label: Angle
      Image: bodyParts/wrist.png
      Values:
        1:
          Label: 15° up - 15° down
          Image: angleIcons/rulaReba/Wrist_15_15_Deg@2x.png
        2:
          Label: 15°+ up OR 15°+ down
          Image: angleIcons/rulaReba/Wrist_15+Up_Deg@2x.png
          Image2: angleIcons/rulaReba/Wrist_15+Down_Deg@2x.png
          Warning: Wrist far too bent
    Twist:
      Type: checkbox
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Twisted
      Image: ~
      Values:
        1:
          Label: Yes
          Image: angleIcons/rulaReba/Wrist_twisted_palm_down@2x.png
          Image2: angleIcons/rulaReba/Wrist_twisted_palm_down@2x.png
        0:
          Label: No

  Leg:
    Score:
      Type: imageSelect
      Base: 1
      MaxInput: ~
      Units: ~
      Label: Angle
      Image: bodyParts/leg.png
      Values:
        1:
          Label: "0"
          Image: angleIcons/rulaReba/Leg_both_down@2x.png
        2:
          Label: 30° - 60°
          Image: angleIcons/rulaReba/Leg_30_60_Deg@2x.png
        3:
          Label: 60°+
          Image: angleIcons/rulaReba/Leg_60+_deg@2x.png
          Warning: Legs bent too much
    UnstableFooting:
      Type: checkbox
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Feet crossed or otherwise unstable on ground
      Image: ~
      Values:
        1:
          Label: Yes
          Image: angleIcons/rulaReba/Leg_one_raised@2x.png
        0:
          Label: No

AdditionalInputs:
  Force:
    Load:
      Type: select
      Base: 0
      MaxInput: ~
      Units: [lbs, kgs]
      Label: Force/Load
      Image: additionalInputs/ForceLoad.png
      Values:
        0:
          Label: < 5 kg
          Score: *acceptable
        1:
          Label: 5 kg - 10 kg
          Score: *medium
        2:
          Label: "> 10 kg"
          Warning: Force/load too high
          Score: *high
    ForceBuildup:
      Type: checkbox
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Shock force, rapid buildup of force, or sudden exertion is required
      Image: additionalInputs/ShockForce.png
      Values:
        1:
          Label: Yes
          Score: *high
        0:
          Label: No
          Score: *acceptable

  Misc:
    CouplingScore:
      Type: select
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Coupling score
      Image: additionalInputs/Coupling.png
      Values:
        0:
          Label: Good
          Score: *acceptable
        1:
          Label: Fair
          Score: *low
        2:
          Label: Poor
          Warning: Coupling is poor
          Score: *medium
        3:
          Label: Unacceptable
          Warning: Coupling is unacceptable
          Score: *high
    BodyPartHeldStatic:
      Type: checkbox
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Static body parts
      Image: additionalInputs/StaticBodyPart.png
      Values:
        1:
          Label: Yes
          Score: *high
        0:
          Label: No
          Score: *acceptable
    RepeatedSmallActions:
      Type: checkbox
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Repeated range actions
      Image: additionalInputs/RepeatedSmallActions.png
      Values:
        1:
          Label: Yes
          Score: *high
        0:
          Label: No
          Score: *acceptable
    RapidPostureChange:
      Type: checkbox
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Rapid posture change
      Image: additionalInputs/RepeatedSmallActions.png
      Values:
        1:
          Label: Yes
          Score: *high
        0:
          Label: No
          Score: *acceptable

Form:
  RiskComponents:
    Groups:
      0:
        Label: Neck
      1:
        Label: Upper Arm
      2:
        Label: Trunk
      3:
        Label: Lower Arm
      4:
        Label: Wrist
      5:
        Label: Leg
    Items:
      0:
        Input: Neck
        Component: Score
        Group: "0"
      1:
        Input: Neck
        Component: SideBend
        Group: "0"
      2:
        Input: Neck
        Component: Twist
        Group: "0"
      3:
        Input: Upper Arm
        Component: Score
        Group: "1"
      4:
        Input: Upper Arm
        Component: Abducted
        Group: "1"
      5:
        Input: Upper Arm
        Component: ShoulderRaised
        Group: "1"
      6:
        Input: Trunk
        Component: Score
        Group: "2"
      7:
        Input: Trunk
        Component: SideBend
        Group: "2"
      8:
        Input: Trunk
        Component: Twist
        Group: "2"
      9:
        Input: Lower Arm
        Component: Score
        Group: "3"
      10:
        Input: Wrist
        Component: Score
        Group: "4"
      11:
        Input: Wrist
        Component: Twist
        Group: "4"
      12:
        Input: Leg
        Component: Score
        Group: "5"
      13:
        Input: Leg
        Component: UnstableFooting
        Group: "5"
  AdditionalInputs:
    Groups:
      0:
        Label: ~
        Inline: True
      1:
        Label: ~
        Inline: True
      2:
        Label: Activity Score
        Inline: True
    Items:
      0:
        Input: Force
        Component: Load
        Group: "0"
      1:
        Input: Force
        Component: ForceBuildup
        Group: "0"
      2:
        Input: Misc
        Component: CouplingScore
        Group: "1"
      3:
        Input: Misc
        Component: BodyPartHeldStatic
        Group: "2"
      4:
        Input: Misc
        Component: RepeatedSmallActions
        Group: "2"
      5:
        Input: Misc
        Component: RapidPostureChange
        Group: "2"
  Postures:
    Groups:
      0:
        Label: Body parts
        Type: progress
    Items:
      0:
        Input: ""
        Component: Trunk
        Image: bodyParts/back.png
        Group: "0"
      1:
        Input: ""
        Component: Neck
        Image: bodyParts/neck.png
        Group: "0"
      2:
        Input: ""
        Component: Lower Arm
        Image: bodyParts/arm.png
        Group: "0"
      3:
        Input: ""
        Component: Upper Arm
        Image: bodyParts/shoulder.png
        Group: "0"
      4:
        Input: ""
        Component: Wrist
        Image: bodyParts/wrist.png
        Group: "0"
      5:
        Input: ""
        Component: Leg
        Image: bodyParts/leg.png
        Group: "0"
  Results:
    Groups:
      0:
        Label: ~
        Type: riskscore
    Items:
      0:
        Input: ""
        Component: Overall
        Group: "0"
        Label: MSD risk score
