constants:
  light_green: &light_green
    Color:
      rgba(109, 208, 163, 1.0)

  green: &green
    Color:
      rgba(241, 196, 15, 1.0)

  orange: &orange
    Color:
      rgba(230, 126, 34, 1.0)

  red: &red
    Color:
      rgba(184, 15, 10, 1.0)

  dark_red: &dark_red
    Color:
      rgba(133, 4, 0, 1.0)

  acceptable: &acceptable
    TranslateText: rosa.score.acceptable
    ShortText: Acceptable
    Text: Further assessment not immediately required
    <<: *light_green
  low: &low
    TranslateText: rosa.score.low
    ShortText: ~
    Text: ~
    <<: *green
  medium: &medium
    TranslateText: rosa.score.medium
    ShortText: ~
    Text: ~
    <<: *orange
  high: &high
    TranslateText: rosa.score.high
    ShortText: High
    Text: Further assessment required as soon as possible
    <<: *red
  vhigh: &vhigh
    TranslateText: rosa.score.vhigh
    ShortText: ~
    Text: ~
    <<: *dark_red

Colors:
  acceptable: *light_green
  low: *green
  medium: *orange
  high: *red
  vhigh: *dark_red

EnvironmentScores:
  Overall:
    1:
      << : *acceptable
    2:
      << : *acceptable
    3:
      << : *acceptable
    4:
      << : *acceptable
    5: 
      << : *high
    6:
      << : *high
    7:
      << : *high
    8:
      << : *high
    9:
      << : *high
    10:
      << : *high
  SeatPanHeightAndDepth:
    2:
      << : *acceptable
    3:
      << : *acceptable
    4: 
      << : *acceptable
    5: 
      << : *high
    6: 
      << : *high
    7:
      << : *high
  ArmsBackRest:
    2:
      << : *acceptable
    3:
      << : *acceptable
    4: 
      << : *acceptable
    5: 
      << : *acceptable
    6: 
      << : *high
    7:
      << : *high
    8:
      << : *high
    9:
      << : *high
  Monitor:
    0:
      << : *acceptable
    1:
      << : *acceptable
    2: 
      << : *acceptable
    3: 
      << : *acceptable
    4: 
      << : *high
    5:
      << : *high
    6:
      << : *high
    7:
      << : *high
  Phone:
    0:
      << : *acceptable
    1:
      << : *acceptable
    2: 
      << : *acceptable
    3: 
      << : *high
    4: 
      << : *high
    5:
      << : *high
    6:
      << : *high
  Mouse:
    0:
      << : *acceptable
    1:
      << : *acceptable
    2: 
      << : *acceptable
    3: 
      << : *acceptable
    4: 
      << : *high
    5:
      << : *high
    6:
      << : *high
    7:
      << : *high
  Keyboard:
    0:
      << : *acceptable
    1:
      << : *acceptable
    2: 
      << : *acceptable
    3: 
      << : *acceptable
    4: 
      << : *high
    5:
      << : *high
    6:
      << : *high
    7:
      << : *high

ComponentValues:
  SeatPanHeightAndDepth:
    ChairHeight:
      1:
        Text: Knees at 90°
        TranslateText: rosa.chair.chair-height-knees-at-90
        Warning: ~
        TranslateWarning: ~
      2:
        Text: Knee angle < 90°
        TranslateText: rosa.chair.chair-height-knees-less-90
        Warning: Too low
        TranslateWarning: rosa.chair.chair-height-too-low
      2.1:
        Text: Knee angle > 90°
        TranslateText: rosa.chair.chair-height-knees-more-90
        Warning: Too high
        TranslateWarning: rosa.chair.chair-height-too-high
      3:
        Text: Not foot contact on ground
        TranslateText: rosa.chair.chair-height-foot-no-contact
        Warning: ~
        TranslateWarning: ~
      Base: 1
      type: select
      TranslateLabel: rosa.chair.chair-height
      label: Chair Height
    ChairInsufficientSpace:
      1:
        Text: Yes
        TranslateText: general.yes
        Warning: No ability to cross legs
        TranslateWarning: rosa.chair.insufficient-space-cross-legs
      0:
        Text: No
        TranslateText: general.no
        Warning: ~
        TranslateWarning: ~
      label: Insufficient space under desk
      type: boolean
      Base: 0
      TranslateLabel: rosa.chair.insufficient-space
    ChairHeightNonAdjustable:
      1:
        Text: Yes
        TranslateText: general.yes
        Warning: ~
        TranslateWarning: ~
      0:
        Text: No
        TranslateText: general.no
        Warning: ~
        TranslateWarning: ~
      label: Chair height non adjustable
      type: boolean
      Base: 0
      TranslateLabel: rosa.chair.height-non-adjustable
    ChairPanDepth:
      1:
        Text: Approximately 3 inches of space between knee and edge of seat
        TranslateText: rosa.chair.pan-depth-3-inch
        Warning: ~
        TranslateWarning: ~
      2:
        Text: Less than 3 inches of space between knee and edge of seat
        TranslateText: rosa.chair.pan-depth-less-3-inch
        Warning: ~
        TranslateWarning: ~
      2.1:
        Text: More than 3 inches of space between knee and edge of seat
        TranslateText: rosa.chair.pan-depth-more-3-inch
        Warning: ~
        TranslateWarning: ~
      Base: 1
      type: select
      TranslateLabel: rosa.chair.pan-depth
      label: Chair Height
    ChairPanNonAdjustable:
      1:
        Text: Yes
        TranslateText: general.yes
        Warning: ~
        TranslateWarning: ~
      0:
        Text: No
        TranslateText: general.no
        Warning: ~
        TranslateWarning: ~
      label: Chair pan non adjustable
      type: boolean
      Base: 0
      TranslateLabel: rosa.chair.pan-non-adjustable
  ArmsBackRest:
    ChairArmrests:
      1:
        Text: Elbows supported in line with shoulders, shoulders relaxed
        TranslateText: rosa.chair.armrests-elbow-supported
        Warning: ~
        TranslateWarning: ~
      2:
        Text: Shoulders shrugged or arms unsupported
        TranslateText: rosa.chair.armrests-shoulders-shrugged
        Warning: ~
        TranslateWarning: ~
      Base: 1
      type: select
      TranslateLabel: rosa.chair.armrests
      label: Armrests
    ChairArmrestHardDamaged:
      1:
        Text: Yes
        TranslateText: general.yes
        Warning: ~
        TranslateWarning: ~
      0:
        Text: No
        TranslateText: general.no
        Warning: ~
        TranslateWarning: ~
      label: Hard/damaged surface
      type: boolean
      Base: 0
      TranslateLabel: rosa.chair.armrest-damaged
    ChairArmrestTooWide:
      1:
        Text: Yes
        TranslateText: general.yes
        Warning: ~
        TranslateWarning: ~
      0:
        Text: No
        TranslateText: general.no
        Warning: ~
        TranslateWarning: ~
      label: Armrests too wide
      type: boolean
      Base: 0
      TranslateLabel: rosa.chair.armrest-to-wide
    ChairArmrestNonAdjustable:
      1:
        Text: Yes
        TranslateText: general.yes
        Warning: ~
        TranslateWarning: ~
      0:
        Text: No
        TranslateText: general.no
        Warning: ~
        TranslateWarning: ~
      label: Armrests non adjustable
      type: boolean
      Base: 0
      TranslateLabel: rosa.chair.armrest-non-adjustable
    ChairBackSupport:
      1:
        Text: Adequate lumbar support
        TranslateText: rosa.chair.back-support-adequate
        Warning: ~
        TranslateWarning: ~
      2:
        Text: No lumbar support
        TranslateText: rosa.chair.back-support-no-lumbar-support
        Warning: ~
        TranslateWarning: ~
      2.1:
        Text: Angled too far back (greated than 110°) or forward (less than 95°)
        TranslateText: rosa.chair.back-support-angled-too-far
        Warning: ~
        TranslateWarning: ~
      2.2:
        Text: No back support
        TranslateText: rosa.chair.back-support-no-back-support
        Warning: ~
        TranslateWarning: ~
      Base: 1
      type: select
      TranslateLabel: rosa.chair.back-support
      label: Back support
    ChairBackSupportSurfaceTooHigh:
      1:
        Text: Yes
        TranslateText: general.yes
        Warning: ~
        TranslateWarning: ~
      0:
        Text: No
        TranslateText: general.no
        Warning: ~
        TranslateWarning: ~
      label: Work surface too high (shoulders shrugged)
      type: boolean
      Base: 0
      TranslateLabel: rosa.chair.back-support-surface-to-high
    ChairBackSupportNonAdjustable:
      1:
        Text: Yes
        TranslateText: general.yes
        Warning: ~
        TranslateWarning: ~
      0:
        Text: No
        TranslateText: general.no
        Warning: ~
        TranslateWarning: ~
      label: Back support non adjustable
      type: boolean
      Base: 0
      TranslateLabel: rosa.chair.back-support-surface-non-adjustable
  Monitor:
    MonitorDistance:
      1:
        Text: Arm's length distance (40-75cm) / Screen at eye
        TranslateText: rosa.chair.monitor-screen-at-eye
        Warning: ~
        TranslateWarning: ~
      2:
        Text: Screen too low (bellow 30°)
        TranslateText: rosa.chair.monitor-screen-too-low
        Warning: ~
        TranslateWarning: ~
      3:
        Text: Screen too high (neck extension)
        TranslateText: rosa.chair.monitor-screen-too-high
        Warning: ~
        TranslateWarning: ~
      Base: 1
      type: select
      TranslateLabel: rosa.computer.monitor-distance
      label: Monitor distance
    MonitorToFar:
      1:
        Text: Yes
        TranslateText: general.yes
        Warning: ~
        TranslateWarning: ~
      0:
        Text: No
        TranslateText: general.no
        Warning: ~
        TranslateWarning: ~
      label: Monitor too far
      type: boolean
      Base: 0
      TranslateLabel: rosa.chair.monitor-too-far
    MonitorNeckTwist:
      1:
        Text: Yes
        TranslateText: general.yes
        Warning: ~
        TranslateWarning: ~
      0:
        Text: No
        TranslateText: general.no
        Warning: ~
        TranslateWarning: ~
      label: Neck twist greater the 30°
      type: boolean
      Base: 0
      TranslateLabel: rosa.chair.monitor-neck-twist
    MonitorGlareOnScreen:
      1:
        Text: Yes
        TranslateText: general.yes
        Warning: ~
        TranslateWarning: ~
      0:
        Text: No
        TranslateText: general.no
        Warning: ~
        TranslateWarning: ~
      label: Glare on screen
      type: boolean
      Base: 0
      TranslateLabel: rosa.chair.monitor-glare-on-screen
    MonitorDocumentsNoHolder:
      1:
        Text: Yes
        TranslateText: general.yes
        Warning: ~
        TranslateWarning: ~
      0:
        Text: No
        TranslateText: general.no
        Warning: ~
        TranslateWarning: ~
      label: Documents (no holder)
      type: boolean
      Base: 0
      TranslateLabel: rosa.chair.monitor-documents-no-holder
  Phone:
    Phone:
      1:
        Text: Headset / One hand on phone & neutral neck posture
        TranslateText: rosa.computer.phone-headset
        Warning: ~
        TranslateWarning: ~
      2:
        Text: To far of reach (outside of 30cm)
        TranslateText: rosa.computer.phone-too-far
        Warning: ~
        TranslateWarning: ~
      Base: 1
      type: select
      TranslateLabel: rosa.computer.phone
      label: Phone
    PhoneNeckShoulder:
      2:
        Text: Yes
        TranslateText: general.yes
        Warning: ~
        TranslateWarning: ~
      0:
        Text: No
        TranslateText: general.no
        Warning: ~
        TranslateWarning: ~
      label: Neck and shoulder hold
      type: boolean
      Base: 0
      TranslateLabel: rosa.computer.phone-neck-shoulder
    PhoneNoHandsFree:
      1:
        Text: Yes
        TranslateText: general.yes
        Warning: ~
        TranslateWarning: ~
      0:
        Text: No
        TranslateText: general.no
        Warning: ~
        TranslateWarning: ~
      label: No hands-free
      type: boolean
      Base: 0
      TranslateLabel: rosa.computer.phone-no-hands-free
  Mouse:
    Mouse:
      1:
        Text: Mouse in line with shoulder
        TranslateText: rosa.computer.mouse-on-line
        Warning: ~
        TranslateWarning: ~
      2:
        Text: Reaching to mouse
        TranslateText: rosa.computer.mouse-reaching
        Warning: ~
        TranslateWarning: ~
      Base: 1
      type: select
      TranslateLabel: rosa.computer.mouse
      label: Mouse
    MouseKeyboardDifferentSurfaces:
      2:
        Text: Yes
        TranslateText: general.yes
        Warning: ~
        TranslateWarning: ~
      0:
        Text: No
        TranslateText: general.no
        Warning: ~
        TranslateWarning: ~
      label: Mouse/keyboard in different surfaces
      type: boolean
      Base: 0
      TranslateLabel: rosa.computer.mouse-keyboard-different-surfaces
    MousePinchGripOnMouse:
      1:
        Text: Yes
        TranslateText: general.yes
        Warning: ~
        TranslateWarning: ~
      0:
        Text: No
        TranslateText: general.no
        Warning: ~
        TranslateWarning: ~
      label: Pinch grip on mouse
      type: boolean
      Base: 0
      TranslateLabel: rosa.computer.mouse-pinch-grip
    MousePalmrest:
      1:
        Text: Yes
        TranslateText: general.yes
        Warning: ~
        TranslateWarning: ~
      0:
        Text: No
        TranslateText: general.no
        Warning: ~
        TranslateWarning: ~
      label: Parmrest in front of mouse
      type: boolean
      Base: 0
      TranslateLabel: rosa.computer.mouse-parmrest
  Keyboard:
    Keyboard:
      1:
        Text: Wrists straight, shoulders relaxed
        TranslateText: rosa.computer.keyboard-wrists-straight
        Warning: ~
        TranslateWarning: ~
      2:
        Text: Wrists extended / Keyboard on positive angle (>15° wrist extension)
        TranslateText: rosa.computer.keyboard-rist-extended
        Warning: ~
        TranslateWarning: ~
      Base: 1
      type: select
      TranslateLabel: rosa.computer.keyboard
      label: Keyboard
    KeyboardDeviation:
      1:
        Text: Yes
        TranslateText: general.yes
        Warning: ~
        TranslateWarning: ~
      0:
        Text: No
        TranslateText: general.no
        Warning: ~
        TranslateWarning: ~
      label: Deviation while typing
      type: boolean
      Base: 0
      TranslateLabel: rosa.computer.keyboard-deviation
    KeyboardTooHigh:
      1:
        Text: Yes
        TranslateText: general.yes
        Warning: ~
        TranslateWarning: ~
      0:
        Text: No
        TranslateText: general.no
        Warning: ~
        TranslateWarning: ~
      label: Keyboard too high / Shoulders shrugged
      type: boolean
      Base: 0
      TranslateLabel: rosa.computer.keyboard-deviation
    KeyboardReachingItems:
      1:
        Text: Yes
        TranslateText: general.yes
        Warning: ~
        TranslateWarning: ~
      0:
        Text: No
        TranslateText: general.no
        Warning: ~
        TranslateWarning: ~
      label: Reaching to overhead items
      type: boolean
      Base: 0
      TranslateLabel: rosa.computer.keyboard-reaching-items
    KeyboardPlatformNonAdjustable:
      1:
        Text: Yes
        TranslateText: general.yes
        Warning: ~
        TranslateWarning: ~
      0:
        Text: No
        TranslateText: general.no
        Warning: ~
        TranslateWarning: ~
      label: Platform non adjustable
      type: boolean
      Base: 0
      TranslateLabel: rosa.computer.keyboard-platform-non-adjustable
  Duration:
    ChairDuration:
      0:
        Text: Worker spends 1-4 hours a day intermittently, or between 30 minutes to 1 hour continuously in the chair
        TranslateText: rosa.chair.duration-less-4-hours
        Warning: ~
        TranslateWarning: ~
      -1:
        Text: Worker spends less than 1 hour a day in the chair throughout the day, or for less than 30 minutes consecutively
        TranslateText: rosa.chair.duration-less-1-hour
        Warning: ~
        TranslateWarning: ~
      1:
        Text: Worker spends more than 4 hours a day in the chair intermittently, or greater than 1 hour consecutively
        TranslateText: rosa.chair.duration-more-4-hours
        Warning: ~
        TranslateWarning: ~
      Base: 1
      type: select
      TranslateLabel: rosa.chair.duration
      label: Chair duration
    MonitorDuration:
      0:
        Text: Use of the monitor between 1-4 hours intermittently, or 30minutes to 1 hour consecutively
        TranslateText: rosa.computer.computer-duration-less-4-hours
        Warning: ~
        TranslateWarning: ~
      -1:
        Text: Use of the monitor less than 1 hour of work done per day intermittently, or less than 30 minutes consecutively
        TranslateText: rosa.computer.computer-duration-less-1-hour
        Warning: ~
        TranslateWarning: ~
      1:
        Text: Use of the monitor of greater than 4 hours per day intermittently, or 1 hour consecutively
        TranslateText: rosa.computer.computer-duration-more-4-hours
        Warning: ~
        TranslateWarning: ~
      Base: 1
      type: select
      TranslateLabel: rosa.computer.computer-duration
      label: Computer duration
    PhoneDuration:
      0:
        Text: Use of the phone between 1-4 hours intermittently, or 30minutes to 1 hour consecutively
        TranslateText: rosa.computer.phone-duration-less-4-hours
        Warning: ~
        TranslateWarning: ~
      -1:
        Text: Use of the phone less than 1 hour of work done per day intermittently, or less than 30 minutes consecutively
        TranslateText: rosa.computer.phone-duration-less-1-hour
        Warning: ~
        TranslateWarning: ~
      1:
        Text: Use of the phone of greater than 4 hours per day intermittently, or 1 hour consecutively
        TranslateText: rosa.computer.phone-duration-more-4-hours
        Warning: ~
        TranslateWarning: ~
      Base: 1
      type: select
      TranslateLabel: rosa.computer.phone-duration
      label: Phone duration
    KeyboardDuration:
      0:
        Text: Keyboard is used between 1-4 hours intermittently, or 30minutes to 1 hour consecutively
        TranslateText: rosa.computer.keyboard-duration-less-4-hours
        Warning: ~
        TranslateWarning: ~
      -1:
        Text: Keyboard is used for 1 hour or less intermittently
        TranslateText: rosa.computer.keyboard-duration-less-1-hour
        Warning: ~
        TranslateWarning: ~
      1:
        Text: Keyboard is used for greater than 4 hours per day intermittently, or 1 hour consecutively
        TranslateText: rosa.computer.keyboard-duration-more-4-hours
        Warning: ~
        TranslateWarning: ~
      Base: 1
      type: select
      TranslateLabel: rosa.computer.keyboard-duration
      label: Keyboard duration
    MouseDuration:
      0:
        Text: Mouse is used between 1-4 hours intermittently, or 30minutes to 1 hour consecutively
        TranslateText: rosa.computer.mouse-duration-less-4-hours
        Warning: ~
        TranslateWarning: ~
      -1:
        Text: Mouse is used for 1 hour or less intermittently, or less than 30 minutes consecutively
        TranslateText: rosa.computer.mouse-duration-less-1-hour
        Warning: ~
        TranslateWarning: ~
      1:
        Text: Mouse is used for greater than 4 hours per day intermittently, or 1 hour consecutively
        TranslateText: rosa.computer.mouse-duration-more-4-hours
        Warning: ~
        TranslateWarning: ~
      Base: 1
      type: select
      TranslateLabel: rosa.computer.mouse-duration
      label: Mouse duration
    
...
