SeriaNumber: 1
Name: Rula
AssessmentName: RULA

Colors:
  light_green: &light_green
    rgba(109, 208, 163, 1.0)

  green: &green
    rgba(241, 196, 15, 1.0)

  orange: &orange
    rgba(230, 126, 34, 1.0)

  red: &red
    rgba(184, 15, 10, 1.0)

Constants:
  acceptable: &acceptable
    Value: Acceptable
    Color: *light_green

  low: &low
    Value: Low
    Color: *green

  medium: &medium
    Value: Medium
    Color: *orange

  high: &high
    Value: High
    Color: *red

Enum: {}

OverallScoreValue: Overall

Metadata: {}

ResultValues:
  Overall:
    Label: Overall Score
    Values:
      1:
        Label: Acceptable
        Score: *acceptable
      2:
        Label: Acceptable
        Score: *acceptable
      3:
        Label: Low
        Score: *low
      4:
        Label: Low
        Score: *low
      5:
        Label: Medium
        Score: *medium
      6:
        Label: Medium
        Score: *medium
      7:
        Label: High
        Score: *high

  Neck:
    Label: Neck
    Values:
      1:
        Label: Acceptable
        Score: *acceptable
      2:
        Label: Low
        Score: *low
      3:
        Label: Medium
        Score: *medium
      4:
        Label: Medium
        Score: *medium
      5:
        Label: High
        Score: *high
      6:
        Label: High
        Score: *high

  Upper Arm:
    Label: Upper Arm
    Values:
      1:
        Label: Acceptable
        Score: *acceptable
      2:
        Label: Low
        Score: *low
      3:
        Label: Medium
        Score: *medium
      4:
        Label: Medium
        Score: *medium
      5:
        Label: High
        Score: *high
      6:
        Label: High
        Score: *high

  Lower Arm:
    Label: Lower Arm
    Values:
      1:
        Label: Low
        Score: *low
      2:
        Label: Medium
        Score: *medium
      3:
        Label: High
        Score: *high

  Trunk:
    Label: Trunk
    Values:
      1:
        Label: Acceptable
        Score: *acceptable
      2:
        Label: Low
        Score: *low
      3:
        Label: Medium
        Score: *medium
      4:
        Label: Medium
        Score: *medium
      5:
        Label: High
        Score: *high
      6:
        Label: High
        Score: *high

  Wrist:
    Label: Wrist
    Values:
      1:
        Label: Acceptable
        Score: *acceptable
      2:
        Label: Low
        Score: *low
      3:
        Label: Medium
        Score: *medium
      4:
        Label: High
        Score: *high

RiskComponents:
  Neck:
    Score:
      Type: imageSelect
      Base: 1
      MaxInput: ~
      Units: ~
      Label: Angle
      Image: bodyParts/neck.png
      Values:
        1:
          Label: 0° - 10° forward
          Image: angleIcons/rulaReba/Neck_0_10_deg@2x.png
          Score: *acceptable
        2:
          Label: 10° - 20° forward
          Image: angleIcons/rulaReba/Neck_10_20_deg@2x.png
          Score: *low
        3:
          Label: 20°+ forward
          Image: angleIcons/rulaReba/Neck_20+_deg@2x.png
          Warning: Neck bent forward too much
          Score: *medium
        4:
          Label: 0°+ backward
          Image: angleIcons/rulaReba/Neck_in_extension@2x.png
          Warning: Neck bent backward
          Score: *high
    SideBend:
      Type: checkbox
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Side bending
      Image: ~
      Values:
        1:
          Label: Yes
          Image: angleIcons/rulaReba/Neck_side_bending@2x.png
          Warning: Neck side bending
          Score: *medium
        0:
          Label: No
          Score: *acceptable
    Twist:
      Type: checkbox
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Twisted
      Image: ~
      Values:
        1:
          Label: Yes
          Image: angleIcons/rulaReba/Neck_Twisted@2x.png
          Warning: Neck twisted
          Score: *medium
        0:
          Label: No
          Score: *acceptable

  Upper Arm:
    Score:
      Type: imageSelect
      Base: 1
      MaxInput: ~
      Units: ~
      Label: Angle
      Image: bodyParts/shoulder.png
      Values:
        1:
          Label: 20° in front - 20° behind
          Image: angleIcons/rulaReba/UpperArm_20_20_deg@2x.png
          Score: *acceptable
        2:
          Label: 20°+ behind OR 20° - 45° in front
          Image: angleIcons/rulaReba/UpperArm_20_deg_extension@2x.png
          Image2: angleIcons/rulaReba/UpperArm_20_45_deg@2x.png
          Score: *low
        3:
          Label: 45° - 90° in front
          Image: angleIcons/rulaReba/UpperArm_45_90_deg@2x.png
          Warning: Upper arm raised high
          Score: *medium
        4:
          Label: 90°+ in front
          Image: angleIcons/rulaReba/UpperArm_90+_deg@2x.png
          Warning: Upper arm raised too high
          Score: *high
    Abducted:
      Type: checkbox
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Abducted
      Image: bodyParts/shoulder.png
      Values:
        1:
          Label: Yes
          Image: angleIcons/rulaReba/UpperArm_abducted@2x.png
          Warning: Shoulder abducted
          Score: *medium
        0:
          Label: No
          Score: *acceptable
    ShoulderRaised:
      Type: checkbox
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Shoulder raised
      Image: bodyParts/shoulder.png
      Values:
        1:
          Label: Yes
          Image: angleIcons/rulaReba/UpperArm_shoulder_raised@2x.png
          Score: *medium
        0:
          Label: No
          Score: *acceptable

  Trunk:
    Score:
      Type: imageSelect
      Base: 1
      MaxInput: ~
      Units: ~
      Label: Angle
      Image: bodyParts/back.png
      Values:
        1:
          Label: 0°
          Image: angleIcons/rulaReba/Trunk_0_deg@2x.png
          Score: *acceptable
        2:
          Label: 0° - 20° forward
          Image: angleIcons/rulaReba/Trunk_0_20_deg@2x.png
          Score: *low
        3:
          Label: 20° - 60° forward
          Image: angleIcons/rulaReba/Trunk_20_60_deg@2x.png
          Warning: Trunk bent forward too much
          Score: *medium
        4:
          Label: 60°+ forward
          Image: angleIcons/rulaReba/Trunk_60+_deg@2x.png
          Warning: Trunk bent forward too much
          Score: *high
    SideBend:
      Type: checkbox
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Side bending
      Image: bodyParts/back.png
      Values:
        1:
          Label: Yes
          Image: angleIcons/rulaReba/Trunk_side_bending@2x.png
          Warning: Trunk side bending
          Score: *medium
        0:
          Label: No
          Score: *acceptable
    Twist:
      Type: checkbox
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Twisted
      Image: bodyParts/back.png
      Values:
        1:
          Label: Yes
          Image: angleIcons/rulaReba/Trunk_Twisted@2x.png
          Warning: Trunk twisted
          Score: *medium
        0:
          Label: No
          Score: *acceptable

  Lower Arm:
    Score:
      Type: imageSelect
      Base: 1
      MaxInput: ~
      Units: ~
      Label: Angle
      Image: bodyParts/arm.png
      Values:
        1:
          Label: 60° - 100°
          Image: angleIcons/rulaReba/LowerArm_60_100_deg@2x.png
          Score: *acceptable
        2:
          Label: 0° - 60° OR 100°+
          Image: angleIcons/rulaReba/LowerArm_0_60_deg@2x.png
          Image2: angleIcons/rulaReba/LowerArm_100+_deg@2x.png
          Score: *medium
    Midline:
      Type: checkbox
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Elbow bent from side of body
      Image: bodyParts/arm.png
      Values:
        1:
          Label: Yes
          Score: *medium
        0:
          Label: No
          Score: *acceptable

  Wrist:
    Score:
      Type: imageSelect
      Base: 1
      MaxInput: ~
      Units: ~
      Label: Angle
      Image: bodyParts/wrist.png
      Values:
        1:
          Label: 0°
          Image: angleIcons/rulaReba/Wrist_0_deg@2x.png
          Score: *acceptable
        2:
          Label: 15° up - 15° down
          Image: angleIcons/rulaReba/Wrist_15_15_Deg@2x.png
          Warning: Wrist bent
          Score: *low
        3:
          Label: 15°+ up OR 15°+ down
          Image: angleIcons/rulaReba/Wrist_15+Up_Deg@2x.png
          Image2: angleIcons/rulaReba/Wrist_15+Down_Deg@2x.png
          Warning: Wrist far too bent
          Score: *medium
    Twist:
      Type: checkbox
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Twisted
      Image: bodyParts/wrist.png
      Values:
        1:
          Label: Yes
          Image: angleIcons/rulaReba/Wrist_twisted_palm_down@2x.png
          Image2: angleIcons/rulaReba/Wrist_twisted_palm_up@2x.png
          Score: *medium
        0:
          Label: No
          Score: *acceptable
    Midline:
      Type: checkbox
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Wrist bent from midline
      Image: bodyParts/wrist.png
      Values:
        1:
          Label: Yes
          Image: angleIcons/rulaReba/Wrist_bent_from_midline@2x.png
          Score: *medium
        0:
          Label: No
          Score: *acceptable

AdditionalInputs:
  Force:
    Arm:
      Type: select
      Base: 0
      MaxInput: ~
      Units: [lbs, kgs]
      Label: Arm Force
      Image: additionalInputs/ArmForceLoad.png
      Values:
        0:
          Label: < 1.8 kg
          Score: *acceptable
        1:
          Label: 1.8 kg - 10 kg
          Score: *medium
        2:
          Label: "> 10 kg"
          Warning: To much weight for an arm
          Score: *high
    Leg:
      Type: select
      Base: 0
      MaxInput: ~
      Units: [lbs, kgs]
      Label: Leg Force
      Image: additionalInputs/LegForceLoad.png
      Values:
        0:
          Label: < 1.8 kg
          Score: *acceptable
        1:
          Label: 1.8 kg - 10 kg
          Score: *medium
        2:
          Label: "> 10 kg"
          Warning: To much weight for a leg
          Score: *high
    ArmSuddenExertion:
      Type: checkbox
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Arm Sudden Exertion
      Image: additionalInputs/ArmForceLoad.png
      Values:
        1:
          Label: Yes
          Score: *high
        0:
          Label: No
          Score: *acceptable
    LegSuddenExertion:
      Type: checkbox
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Leg Sudden Exertion
      Image: additionalInputs/LegForceLoad.png
      TooltipText: Legs are usually the most affected by sudden exertion
      Values:
        1:
          Label: Yes
          Score: *high
        0:
          Label: No
          Score: *acceptable
  Misc:
    LegsSupported:
      Type: checkbox
      Base: 1
      MaxInput: ~
      Units: ~
      Label: Legs Supported
      Image: additionalInputs/LegMuscleUse.png
      Values:
        1:
          Label: Yes
          Score: *acceptable
        0:
          Label: No
          Score: *high
  Muscle Use:
    Arm:
      Type: select
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Arms / Muscle Use
      Image: additionalInputs/ArmMuscleUse.png
      Values:
        0:
          Label: Holds still
          Score: *acceptable
        1:
          Label: Moves 4 times/min
          Score: *high
    Leg:
      Type: select
      Base: 0
      MaxInput: ~
      Units: ~
      Label: Legs / Muscle Use
      Image: additionalInputs/LegMuscleUse.png
      Values:
        0:
          Label: Holds still
          Score: *acceptable
        1:
          Label: Moves 4 times/min
          Score: *high
Form:
  RiskComponents:
    Groups:
      0:
        Label: Neck
      1:
        Label: Upper Arm
      2:
        Label: Trunk
      3:
        Label: Lower Arm
      4:
        Label: Wrist
    Items:
      0:
        Input: Neck
        Component: Score
        Group: "0"
      1:
        Input: Neck
        Component: SideBend
        Group: "0"
      2:
        Input: Neck
        Component: Twist
        Group: "0"
      3:
        Input: Upper Arm
        Component: Score
        Group: "1"
      4:
        Input: Upper Arm
        Component: Abducted
        Group: "1"
      5:
        Input: Upper Arm
        Component: ShoulderRaised
        Group: "1"
      6:
        Input: Trunk
        Component: Score
        Group: "2"
      7:
        Input: Trunk
        Component: SideBend
        Group: "2"
      8:
        Input: Trunk
        Component: Twist
        Group: "2"
      9:
        Input: Lower Arm
        Component: Score
        Group: "3"
      10:
        Input: Wrist
        Component: Score
        Group: "4"
      11:
        Input: Wrist
        Component: Twist
        Group: "4"
  AdditionalInputs:
    Groups:
      0:
        Label: Forces Involved
      1:
        Label: Muscle Use
    Items:
      0:
        Component: Arm
        Input: Force
        Group: "0"
      1:
        Component: ArmSuddenExertion
        Input: Force
        Group: "0"
      2:
        Component: Leg
        Input: Force
        Group: "0"
      3:
        Component: LegSuddenExertion
        Input: Force
        Group: "0"
      4:
        Component: Arm
        Input: Muscle Use
        Group: "1"
      5:
        Component: Leg
        Input: Muscle Use
        Group: "1"
      6:
        Component: LegsSupported
        Input: Misc
        Group: "1"
  Postures:
    Groups:
      0:
        Label: Body parts
        Type: progress
    Items:
      0:
        Input: ""
        Component: Trunk
        Image: bodyParts/back.png
        Group: "0"
      1:
        Input: ""
        Component: Neck
        Image: bodyParts/neck.png
        Group: "0"
      2:
        Input: ""
        Component: Lower Arm
        Image: bodyParts/arm.png
        Group: "0"
      3:
        Input: ""
        Component: Upper Arm
        Image: bodyParts/shoulder.png
        Group: "0"
      4:
        Input: ""
        Component: Wrist
        Image: bodyParts/wrist.png
        Group: "0"
  Results:
    Groups:
      0:
        Label: ~
        Type: riskscore
    Items:
      0:
        Input: ""
        Component: Overall
        Group: "0"
        Label: MSD risk score
  CanGenerate:
    Report: true
    Worksheet: true
    Powerpoint: true
    Csv: true
    AIRecommendations: true
    Project: true
